import streamlit as st
import json
from helper_function import applicant_query_handler

from utility import check_password

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    page_title="Buying a Resale Flat",
    page_icon="🏠"
)

# Do not continue if check_password is not True.  
if not check_password():  
    st.stop()

# endregion <--------- Streamlit App Configuration --------->

st.title("Clara")

# Use clear_on_submit to reset the form fields after submission
form = st.form(key="form", clear_on_submit=True)
form.subheader("Hello! I'm Clara, your HDB virtual assistant.")

user_prompt = form.text_area("What would you like to know about buying a resale flat?", height=200)

submitted = form.form_submit_button("Submit")

if submitted:
    with st.spinner("**Gathering information...**"):
        st.toast(f"User Input Submitted - {user_prompt}")
        response = applicant_query_handler.ask_agent(user_prompt)  # Calls the helper function
        with st.chat_message("user", avatar="👤"):
            st.write(user_prompt)
        with st.chat_message("assistant", avatar="🏠"):
            st.write(response.raw)  # Displays the response generated by the CrewAI

# Create an expander with the label "Click to see message"
with st.expander("Disclaimer"):
    # Markdown text inside the expander
    st.markdown("""
            **IMPORTANT NOTICE:** This web application is a prototype developed for **educational purposes only.** The information provided here is **NOT intended for real-world usage** and should not be relied upon for making any decisions, especially those related to financial, legal, or healthcare matters.
            
            **Furthermore, please be aware that the LLM may generate inaccurate or incorrect information. You assume full responsibility for how you use any generated output.**
            
            Always consult with qualified professionals for accurate and personalized advice.
    """)